[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson @ ^7.1.0
    fastled/FastLED @ ^3.9.8
build_flags =
    -D APP_FW_VERSION=\"0.1.0\"
    -D APP_API_VERSION=\"1.0\"
